export { default as Admin } from "./Admin/Admin"
export { default as Collections } from "./Collections/Collections"
export { default as Home } from "./Home/Home"
// export { default as IcrcScan } from "./icrc_scan/IcrcScan"
// export { default as ListProject } from "./list_project/ListProject"
export { default as NotFound } from "./NotFound/NotFound"
export { default as Profile } from "./profile/Profile"
export { default as Project } from "./project/Project"
export { default as Projects } from "./projects/Projects"
// export { default as Proposal } from "./proposal/Proposal"
// export { default as Proposals } from "./proposals/Proposals"
