export { default as Admin } from "./Admin/Admin"
export { default as AdminCollections } from "./Admin/AdminCollections"
export { default as AdminProjects } from "./Admin/AdminProjects"
export { default as AdminUsers } from "./Admin/AdminUsers"
export { default as Collections } from "./Collections/Collections"
export { default as Home } from "./Home/Home"
export { default as ListProject } from "./ListProject/ListProject"
export { default as NotFound } from "./NotFound/NotFound"
export { default as Profile } from "./Profile/Profile"
export { default as Project } from "./Project/Project"
export { default as Projects } from "./Projects/Projects"
export { default as Promote } from "./Promote/Promote"
export { default as Stats } from "./Stats/Stats"

// legal
export { default as CookiePolicy } from "./Cookies/CookiePolicy"
export { default as PrivacyPolicy } from "./Privacy/PrivacyPolicy"
export { default as TermsOfService } from "./Terms/TermsOfService"
