import { Opt, Principal, Record, Vec, bool, nat64, nat8, text } from "azle"

export const ProjectId = text

export const ProjectData = Record({
  id: text,
  submittedBy: text,
  createdAt: text,
  updatedAt: text,
  name: text,
  description: text,
  category: Vec(text),
  logo: text,
  website: text,
  canister: text,
  twitter: text,
  discord: text,
  telegram: text,
  github: text,
  medium: text,
  dscvr: text,
  distrikt: text,
  openchat: text,
  taggr: text,
  seers: text,
  nuance: text,
  catalyze: text,
  funded: text,
  app: text,
  docs: text,
  faq: text,
  whitepaper: text,
  grantee: bool,
  archived: bool,
  nftSaleDate: text,
  nftSaleUrl: text,
  nftUnits: text,
  nftUnitPrice: text,
  nftMarketEntrepot: text,
  nftMarketCcc: text,
  nftMarketYumi: text,
  nftRarityDgdg: text,
  nftStatsNftgeek: text,
  nftImg1: text,
  nftImg2: text,
  nftImg3: text,
  nftImg4: text,
  upvotedBy: Vec(text),
})

export const ProjectProposal = Record({
  id: ProjectId,
  proposalNumber: nat64,
  proposer: Principal,
  projectData: ProjectData,
})
