[
    // {
    //     id: "nnsdao",
    //     name: "Nnsdao",
    //     category: "DAOs",
    //     website: "https://www.icpscan.co/",
    //     canister: "https://sznps-4aaaa-aaaah-qab2a-cai.ic0.app/",
    //     logo: "",
    //     cover: "",
    //     twitter: "https://twitter.com/NnsDaos",
    //     github: "https://github.com/NnsDao",
    //     telegram: "https://t.me/nnsdaos",
    //     slack: "",
    //     discord: "",
    //     medium: "",
    //     dscvr: "",
    //     description: "Nnsdao: the boundaryless autonomous organization.",
    //     twitterHandle: "NnsDaos",
    // },
    // {
    //     id: "tacen",
    //     name: "Tacen",
    //     category: "Infrastructure",
    //     stage: "In development 🛠️",
    //     website: "https://tacen.com/",
    //     canister: "",
    //     logo: "https://i.postimg.cc/x1c392tj/tacen.jpg",
    //     cover: "https://i.postimg.cc/4xqbdSS6/tacen-cover.jpg",
    //     twitter: "https://twitter.com/tacen_app",
    //     github: "",
    //     telegram: "https://t.me/tacen_app",
    //     slack: "",
    //     discord: "",
    //     medium: "https://dfistarter.medium.com/",
    //     country: "",
    //     description: "Featured on dfinity.org/techcrunch and Bloomberg TV as part of the Mercury Genesis event, Tacen is building it's hDEX exchange architecture and decentralized settlement layer leveraging DFINITY canisters to scale its infrastructure. Their goal is to create the first community operated settlement layer for multiple future exchange platforms.",
    //     founder: "",
    //     founderLink: "",
    //     twitterHandle: "tacen_app",
    // },
    // {
    //     id: "super-icp-party",
    //     name: "Super ICP Party",
    //     category: "Games",
    //     website: "",
    //     canister: "https://dqnbo-kiaaa-aaaad-qak2a-cai.raw.ic0.app/",
    //     logo: "https://i.postimg.cc/T1jDTp3w/super-icp-party-cover.jpg",
    //     cover: "https://i.postimg.cc/T1jDTp3w/super-icp-party-cover.jpg",
    //     twitter: "",
    //     github: "",
    //     telegram: "",
    //     slack: "",
    //     discord: "",
    //     medium: "",
    //     description: "",
    //     twitterHandle: "",
    // },

    // {
    //     id: "",
    //     name: "",
    //     category: "",
    //     website: "",
    //     canister: "",
    //     logo: "",
    //     cover: "",
    //     twitter: "",
    //     github: "",
    //     telegram: "",
    //     slack: "",
    //     discord: "",
    //     medium: "",
    //     description: "",
    //     twitterHandle: "",
    // },
]

// Categories: Play-to-earn, ...