export const data = [
    {
        id: "modclub",
        name: "Modclub",
        category: "dApps",
        website: "http://modclub.app/",
        canister: "https://ljyte-qiaaa-aaaah-qaiva-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/hvXgLC0L/modclub-logo.jpg",
        cover: "https://i.postimg.cc/QCvD0p6R/modclub-cover.jpg",
        twitter: "https://twitter.com/ModclubApp",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "Modclub lets you earn rewards for moderating user generated content on the Internet Computer",
        twitterHandle: "ModclubApp",
    },
    {
        id: "icpmeet",
        name: "ICPmeet",
        category: "Social Networks",
        website: "https://www.icpmeet.com/",
        canister: "",
        logo: "https://i.postimg.cc/sgHNCVPJ/icpmeet-logo.png",
        cover: "https://i.postimg.cc/nLswH60f/icpmeet-cover.jpg",
        twitter: "https://twitter.com/icpmeet",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "ICPMEET is a decentralized social application built on Dfinity. It is like a tinder. You can meet encrypted friends from all over the world without being restricted by distance and network, and your personal information and data are in your control.",
        twitterHandle: "icpmeet",
    },
    {
        id: "plug",
        name: "Plug",
        category: "Wallets",
        website: "https://plugwallet.ooo/",
        canister: "",
        logo: "https://i.postimg.cc/T1VTjDz1/plug-logo.jpg",
        cover: "https://i.postimg.cc/28xzVndX/plug-cover.jpg",
        twitter: "https://twitter.com/plug_wallet",
        github: "",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/yVEcEzmrgm",
        medium: "",
        description: "Your Plug into the #InternetComputer Smiling face with sunglasses Identity + Wallet in one Principal ID Man mage Hold, send, swap, deposit cycles & ICP and log into IC apps in one click!",
        twitterHandle: "plug_wallet",
    },
    {
        id: "openchat",
        name: "OpenChat",
        category: "Social Networks",
        stage: "Launched 🚀",
        website: "https://oc.app/",
        canister: "7e6iv-biaaa-aaaaf-aaada-cai.ic0.app",
        logo: "https://i.postimg.cc/76yYgmk2/openchat.jpg",
        cover: "https://i.postimg.cc/prsW-Mvnf/openchat-cover.jpg",
        twitter: "https://twitter.com/OpenChat",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        country: "",
        description: "Chat. On the blockchain. In real time. Made possible by the #InternetComputer. The future is now. Join in!",
        founder: "",
        founderLink: "",
        twitterHandle: "OpenChat",
    },
    {
        id: "ensofinance",
        name: "EnsoFinance",
        category: "DeFi",
        website: "https://www.enso.finance/",
        canister: "",
        logo: "https://i.postimg.cc/vBrbYF12/ensofinance-logo.png",
        cover: "https://i.postimg.cc/Fzhm1W3r/ensofinance-cover.jpg",
        twitter: "https://twitter.com/EnsoFinance",
        github: "",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/y48Yp6Y4QX",
        medium: "https://ensofinance.medium.com/",
        description: "Discover and create open DeFi metastrategies.",
        twitterHandle: "EnsoFinance",
    },
    {
        id: "dscvr",
        name: "dscvr.one",
        category: "Social Networks",
        website: "https://dscvr.one/",
        canister: "h5aet-waaaa-aaaab-qaamq-cai.raw.ic0.app",
        logo: "https://i.postimg.cc/ZqN5BX1m/dscvr.jpg",
        cover: "https://i.postimg.cc/zG6ffq2p/dscvr-cover.jpg",
        twitter: "https://twitter.com/DscvrO",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "a completely decentralized social content platform running on the #InternetComputer ... beta preview started!",
        twitterHandle: "DscvrO",
    },
    {
        id: "toniqlabs",
        name: "toniqlabs",
        category: "dApps",
        website: "https://toniqlabs.com/",
        canister: "https://igpeu-waaaa-aaaad-qaava-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/903RM1RM/toniqlabs-logo.jpg",
        cover: "https://i.postimg.cc/v89xjRk6/toniqlabs-cover.jpg",
        twitter: "https://twitter.com/toniqlabs",
        github: "",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/NCdK8TueUe",
        medium: "",
        description: "We build professional tools and services on the decentralized web",
        twitterHandle: "toniqlabs",
    },
    {
        id: "capsulesocial",
        name: "Capsule Social",
        category: "Social Networks",
        stage: "In development 🛠️",
        website: "https://capsule.social/",
        canister: "",
        logo: "https://i.postimg.cc/pT8pfLXV/capsule-social-logo.jpg",
        cover: "https://i.postimg.cc/Vv85DPdq/capsule-social-cover.jpg",
        twitter: "https://twitter.com/CapsuleSoc",
        github: "",
        telegram: "",
        slack: "",
        discord: "https://discord.com/invite/HhVbaD2BHY",
        medium: "",
        country: "",
        description: "Decentralized discourse",
        founder: "Nadim Kobeissi",
        founderLink: "https://twitter.com/kaepora",
        twitterHandle: "CapsuleSoc",
    },
    {
        id: "dank",
        name: "Dank",
        category: "DeFi",
        website: "https://dank.ooo/",
        canister: "",
        logo: "https://i.postimg.cc/jj5JkDYs/dank-logo.jpg",
        cover: "https://i.postimg.cc/529H6X0w/dank-cover.jpg",
        twitter: "https://twitter.com/dank_ois",
        github: "https://github.com/Psychedelic/dank",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/yVEcEzmrgm",
        medium: "",
        description: "Dank is a collection Open Internet Services on the #InternetComputer, including the Cycles Token (XTC) for holding & using cycles with just a Principal ID.",
        twitterHandle: "dank_ois",
    },
    {
        id: "distrikt",
        name: "distrikt",
        category: "Social Networks",
        website: "https://distrikt.io/",
        canister: "https://c7fao-laaaa-aaaae-aaa4q-cai.ic0.app/",
        logo: "https://i.postimg.cc/YqcjBq5f/distrikt-app-logo.jpg",
        cover: "https://i.postimg.cc/9FG0mHV3/distrikt-app-cover.jpg",
        twitter: "https://twitter.com/DistriktApp",
        github: "",
        telegram: "https://t.me/DistriktApp",
        slack: "",
        discord: "",
        medium: "https://medium.com/distrikt",
        description: "A decentralized, professional social media network that empowers users to own and control their identity and data. Learn more https://distrikt.io",
        twitterHandle: "DistriktApp",
    },
    {
        id: "tacen",
        name: "tacen",
        category: "DeFi",
        website: "https://tacen.com/",
        canister: "",
        logo: "https://i.postimg.cc/sgh8dPGw/tacen-logo.jpg",
        cover: "https://i.postimg.cc/tTXmxLSM/tacen-cover.jpg",
        twitter: "https://twitter.com/tacen_app",
        github: "",
        telegram: "https://t.me/tacen_app",
        slack: "",
        discord: "https://discord.gg/y48Yp6Y4QX",
        medium: "https://ensofinance.medium.com/",
        description: "Building the next generation of crypto exchanges. #hDEX",
        twitterHandle: "tacen_app",
    },
    {
        id: "dfistarter",
        name: "DfiStarter",
        category: "Infrastructure",
        stage: "In development 🛠️",
        website: "https://dfistarter.io/",
        canister: "",
        logo: "https://i.postimg.cc/ZRphPMzh/dfistarter.jpg",
        cover: "https://i.postimg.cc/yxKCLy73/dfistarter-cover.jpg",
        twitter: "https://twitter.com/DfiStarterPad",
        github: "",
        telegram: "https://t.me/DfiStarterOfficial",
        slack: "",
        discord: "",
        medium: "https://dfistarter.medium.com/",
        country: "",
        description: "The first IDO platform on Dfinity, providing not only fund raise services, PR & Marketing, but also tech support to projects planning to develop on Dfinity.",
        founder: "",
        founderLink: "",
        twitterHandle: "DfiStarterPad",
    },
    {
        id: "bunchd",
        name: "Bunchd",
        category: "Social Networks",
        website: "",
        canister: "",
        logo: "https://i.postimg.cc/wjcjcgt9/bunchd-logo.jpg",
        cover: "https://i.postimg.cc/FHQKL7HP/bunchd-cover.jpg",
        twitter: "https://twitter.com/GetBunchd",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "Create, Collaborate, and Earn on the Subscription Platform controlled by Creators.",
        twitterHandle: "GetBunchd",
    },
    {
        id: "icpswap",
        name: "ICPSwap",
        category: "DeFi",
        website: "https://www.icpswap.com/",
        canister: "https://3pbcj-viaaa-aaaah-qaajq-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/x8X5GYKt/icpswap-logo.jpg",
        cover: "https://i.postimg.cc/br4T3Mg8/icpswap-cover.jpg",
        twitter: "https://twitter.com/ICPSwap",
        github: "",
        telegram: "https://t.me/ICPSwap_Official",
        slack: "",
        discord: "",
        medium: "https://icpswap.medium.com/",
        dscvr: "https://h5aet-waaaa-aaaab-qaamq-cai.raw.ic0.app/p/icpswap",
        description: "ICPSwap #DFINITY. The Hub of Future Decentralized Finance.",
        twitterHandle: "ICPSwap",
    },
    {
        id: "dfinity-explorer",
        name: "DFINITY Explorer",
        category: "Explorers",
        website: "https://www.dfinityexplorer.org/",
        canister: "",
        logo: "https://i.postimg.cc/yd51YNGy/dfinity-explorer-logo.png",
        cover: "https://i.postimg.cc/prF29Hbb/dfinity-explorer-cover.jpg",
        twitter: "https://twitter.com/dfinityexplorer",
        github: "https://github.com/dfinityexplorer/dfinityexplorer-dashboard",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "Home of http://dfinityexplorer.org, an open-source network dashboard for the Internet Computer. Follow for IC and $ICP-related news. Community run, not official",
        twitterHandle: "dfinityexplorer",
    },
    {
        id: "portal",
        name: "Portal",
        category: "Social Networks",
        website: "https://h5aet-waaaa-aaaab-qaamq-cai.raw.ic0.app/post/115101/portal-live-stream-on-the-ic",
        canister: "",
        logo: "https://i.postimg.cc/26PGXbVX/portal-cover.jpg",
        cover: "https://i.postimg.cc/26PGXbVX/portal-cover.jpg",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/cJZfHEZZUk",
        medium: "",
        description: "Portal is an Internet Computer app that is bringing live streaming to the IC! Think Twitch but completely decentralized and able to use tokens and wallets natively! Looking for people to come hang out in Discord and contribute to the community while we grow!",
        twitterHandle: "",
    },
    {
        id: "icp-neuron-calculator",
        name: "ICP Neuron Calculator",
        category: "Tools",
        website: "https://networknervoussystem.com/",
        canister: "",
        logo: "https://i.postimg.cc/L8JcxyG5/icp-neuron-calculator-logo.jpg",
        cover: "https://i.postimg.cc/Z5X128hc/icp-neuron-calculator-cover.jpg",
        twitter: "https://twitter.com/NNSystem",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "Long time Internet Computer fan, creator of http://networknervoussystem.com and writer of https://allthingsinternetcomputer.substack.com",
        twitterHandle: "NNSystem",
    },
    {
        id: "axon",
        name: "Axon",
        category: "Tools",
        website: "https://axon.ooo/",
        canister: "",
        logo: "https://i.postimg.cc/mD7Zd4kL/axon-logo.jpg",
        cover: "https://i.postimg.cc/qq0JSF68/axon-cover.jpg",
        twitter: "https://twitter.com/axon_ooo",
        github: "https://github.com/FloorLamp/axon",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "Multi-user multi-neuron management service",
        twitterHandle: "axon_ooo",
    },
    {
        id: "ic-drive",
        name: "IC Drive",
        category: "dApps",
        website: "http://icdrive.co/",
        canister: "https://rglue-kyaaa-aaaah-qakca-cai.ic0.app/",
        logo: "https://i.postimg.cc/RZqMkKhb/ic-drive-logo.jpg",
        cover: "https://i.postimg.cc/xjMqrDWk/ic-drive-cover.png",
        twitter: "https://twitter.com/icDrive",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "A decentralized private storage app built on the Internet Computer. Store and securely share every type of file.",
        twitterHandle: "icDrive",
    },
    {
        id: "aedile",
        name: "aedile",
        category: "dApps",
        website: "",
        canister: "",
        logo: "https://i.postimg.cc/cLjs0C81/aedile-logo.jpg",
        cover: "https://i.postimg.cc/1zqytSpG/aedile-cover.jpg",
        twitter: "https://twitter.com/aedile_ic",
        github: "https://github.com/aedile-ic",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "A project management tool made by @esensconsulting based on the #InternetComputer made by #Dfinity...beta coming soon",
        twitterHandle: "aedile_ic",
    },
    {
        id: "fleek-co",
        name: "Fleek.co",
        category: "Infrastructure",
        website: "https://fleek.co/",
        canister: "",
        logo: "https://i.postimg.cc/HskcLJjb/fleek-co-logo.jpg",
        cover: "https://i.postimg.cc/0y6zpLYQ/fleek-co-cover.jpg",
        twitter: "https://twitter.com/FleekHQ",
        github: "https://github.com/FleekHQ",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/yVEcEzmrgm",
        medium: "",
        description: "Effortlessly build Open Web sites & apps. Hosting, ENS, Storage, Pinning! Built on the Internet Computer, IPFS, Ethereum, Filecoin, etc.",
        twitterHandle: "FleekHQ",
    },
    {
        id: "fleek-ooo",
        name: "Fleek.ooo",
        category: "dApps",
        website: "https://fleek.ooo/",
        canister: "",
        logo: "https://i.postimg.cc/m2pc1bFJ/fleek-ooo-logo.jpg",
        cover: "https://i.postimg.cc/wjS7F02k/fleek-ooo-cover.jpg",
        twitter: "https://twitter.com/fleek_ois",
        github: "",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/yVEcEzmrgm",
        medium: "",
        description: "Easily build, deploy, and manage canisters, cycles, apps, & infrastructure on DFINITY's Internet Computer.",
        twitterHandle: "fleek_ois",
    },
    {
        id: "ic-rocks",
        name: "ic.rocks",
        category: "Tools",
        website: "https://ic.rocks/",
        canister: "",
        logo: "https://i.postimg.cc/jCYRPFtW/ic-rocks-logo.jpg",
        cover: "https://i.postimg.cc/dtGypM7x/ic-rocks-cover.jpg",
        twitter: "https://twitter.com/ic_rocks",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "The Internet Computer rocks. Analytics, explorer, and tools",
        twitterHandle: "ic_rocks",
    },
    {
        id: "motoko-playground",
        name: "Motoko Playground",
        category: "Tools",
        website: "",
        canister: "https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/4yMczZSJ/motoko-playground-logo.png",
        cover: "https://i.postimg.cc/Zqjpd98y/motoko-playground-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "",
        twitterHandle: "",
    },
    {
        id: "cycle-dao",
        name: "cycle_dao",
        category: "DAOs",
        website: "https://cycledao.xyz/",
        canister: "",
        logo: "https://i.postimg.cc/9fmFLKTZ/cycle-dao-logo.png",
        cover: "https://i.postimg.cc/rmzyk4fp/cycle-dao-cover.jpg",
        twitter: "https://twitter.com/cycle_dao",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "We support autonomous open services on the Internet Computer",
        twitterHandle: "cycle_dao",
    },
    {
        id: "dfinance",
        name: "DFinance",
        category: "DeFi",
        website: "https://dfinance.ai/",
        canister: "",
        logo: "https://i.postimg.cc/7PKjgZyM/dfinance-logo.jpg",
        cover: "https://i.postimg.cc/m2qq5pkP/dfinance-cover.jpg",
        twitter: "https://twitter.com/DFinance_AI",
        github: "https://github.com/dfinance-tech",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        dscvr: "",
        description: "Building DeFi infrastructure for the DFINITY Internet Computer.",
        twitterHandle: "DFinance_AI",
    },
    {
        id: "infinityswap",
        name: "InfinitySwap",
        category: "DeFi",
        website: "https://infinityswap.one/",
        canister: "",
        logo: "https://i.postimg.cc/Kv4wQhGX/infinityswap-logo.jpg",
        cover: "https://i.postimg.cc/tT2vt28C/infinityswap-cover.jpg",
        twitter: "https://twitter.com/infinity_swap",
        github: "",
        telegram: "https://t.me/infinityswapofficial",
        slack: "",
        discord: "",
        medium: "",
        dscvr: "",
        description: "A platform to create, stake and swap Dfinity Tokens",
        twitterHandle: "infinity_swap",
    },
    {
        id: "internet-computer-dashboard",
        name: "Internet Computer Dashboard",
        category: "Explorers",
        website: "https://dashboard.internetcomputer.org/",
        canister: "",
        logo: "https://i.postimg.cc/8PvsLFRn/internet-computer-dashboard-logo.png",
        cover: "https://i.postimg.cc/Sx7stwt6/internet-computer-dashboard-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "",
        twitterHandle: "",
    },
    {
        id: "icpunks",
        name: "ICPunks",
        category: "NFTs",
        website: "https://icpunks.com/",
        canister: "",
        logo: "https://i.postimg.cc/xjJHGN9Y/icpunks-logo.jpg",
        cover: "https://i.postimg.cc/j5WWhB0v/icpunks-cover.jpg",
        twitter: "https://twitter.com/ICPunks",
        github: "https://github.com/stopak/ICPunks/tree/dev",
        telegram: "",
        slack: "",
        discord: "https://discord.gg/m8QWD7m62h",
        medium: "",
        description: "First NFTs on the Internet Computer. 10,000 randomly generated, unique collectible clowns.",
        twitterHandle: "ICPunks",
    },
    {
        id: "canlista",
        name: "Canlista",
        category: "Infrastructure",
        website: "",
        canister: "https://k7gat-daaaa-aaaae-qaahq-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/R08fD0Ps/canlista-logo.png",
        cover: "https://i.postimg.cc/52Cs3ZNM/canlista-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "> the Internet Computer community canister registry",
        twitterHandle: "",
    },
    {
        id: "the-nft-village",
        name: "The NFT Village",
        category: "NFTs",
        website: "",
        canister: "https://nntkg-vqaaa-aaaad-qamfa-cai.ic.fleek.co/",
        logo: "https://i.postimg.cc/43xHYmWD/nft-village-logo.jpg",
        cover: "https://i.postimg.cc/CLCRJjXy/nft-village-cover.jpg",
        twitter: "https://twitter.com/NFT_Village",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "A friendly place for all of your favorite NFTs on the Internet Computer",
        twitterHandle: "NFT_Village",
    },
    {
        id: "canistore",
        name: "Canistore",
        category: "Social Networks",
        website: "https://canistore.io/",
        canister: "",
        logo: "https://i.postimg.cc/bvmYWgHM/canistore-logo.jpg",
        cover: "https://i.postimg.cc/jSK7r8Pd/canistore-cover.jpg",
        twitter: "https://twitter.com/canistore",
        github: "",
        telegram: "http://t.me/canistore",
        slack: "",
        discord: "",
        medium: "https://medium.com/@canistore",
        description: "Next-gen #SocialStore powered by @DFINITY, empowered by community #JoinTheFrequency",
        twitterHandle: "canistore",
    },
    {
        id: "earth-wallet",
        name: "Earth Wallet",
        category: "Wallets",
        website: "https://www.earthwallet.io/",
        canister: "",
        logo: "https://i.postimg.cc/vBjtBB2Q/earthwallet-logo.jpg",
        cover: "https://i.postimg.cc/LstfZrsJ/earthwallet-cover.jpg",
        twitter: "https://twitter.com/EarthWallet",
        github: "https://github.com/earth-association",
        telegram: "https://t.me/earthwallet",
        slack: "",
        discord: "",
        medium: "",
        description: "Bringing Crypto Back Down to Earth. Join us on our mission. Register today and learn more.",
        twitterHandle: "EarthWallet",
    },
    {
        id: "deckdeckgo",
        name: "DeckDeckGo",
        category: "dApps",
        website: "https://deckdeckgo.com/en/",
        canister: "",
        logo: "https://i.postimg.cc/ZnWMgzbV/deckdeckgo-logo.jpg",
        cover: "https://i.postimg.cc/sgJC5yvh/deckdeckgo-cover.jpg",
        twitter: "https://twitter.com/deckdeckgo",
        github: "https://github.com/deckgo/deckdeckgo",
        telegram: "",
        slack: "https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY",
        discord: "",
        medium: "",
        description: "Create, present and share slides that interact with your audience.",
        twitterHandle: "deckdeckgo",
    },
    {
        id: "waterslide-app",
        name: "waterslide.app",
        category: "DeFi",
        website: "https://waterslide.app/",
        canister: "",
        logo: "https://i.postimg.cc/CKp2FZjY/waterslide-app-logo.jpg",
        cover: "https://i.postimg.cc/yNhbWVPR/waterslide-app-cover.png",
        twitter: "https://twitter.com/waterslide_app",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        dscvr: "",
        description: "Frontend to interact with the @LiquityProtocol.Powered by @dfinity",
        twitterHandle: "waterslide_app",
    },
    {
        id: "rise-of-the-magni",
        name: "Rise of the Magni",
        category: "Games",
        website: "https://riseofthemagni.com/",
        canister: "",
        logo: "https://i.postimg.cc/G3y8T0jm/rise-of-the-magni-logo.png",
        cover: "https://i.postimg.cc/bNfGQ66H/rise-of-the-magni-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "Welcome to the world of Tora, where adorable heroes named Magni fight it out on the battlefield!",
        twitterHandle: "",
    },
    {
        id: "Metaverse",
        name: "Metaverse",
        category: "Games",
        website: "",
        canister: "https://lc7ip-3iaaa-aaaah-aafva-cai.ic0.app/",
        logo: "https://i.postimg.cc/kgctMxvN/metaverse-logo.png",
        cover: "https://i.postimg.cc/Kz29f3wc/metaverse-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "The metaverse is metacool",
        twitterHandle: "",
    },
    {
        id: "saga-tarot",
        name: "Saga Tarot",
        category: "Games",
        website: "",
        canister: "https://l2jyf-nqaaa-aaaah-qadha-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/C5kz3DKq/saga-tarrot-logo.png",
        cover: "https://i.postimg.cc/hjfs48kG/saga-tarrot-cover.jpg",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "",
        twitterHandle: "",
    },
    {
        id: "sudoku",
        name: "sudoku",
        category: "Games",
        website: "",
        canister: "https://omro3-5yaaa-aaaad-qalta-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/13xScfW4/sudoku-cover.png",
        cover: "https://i.postimg.cc/13xScfW4/sudoku-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "",
        twitterHandle: "",
    },
    {
        id: "cycles-bet",
        name: "Cycles Bet",
        category: "Games",
        website: "https://cycles.bet/",
        canister: "https://stz5m-sqaaa-aaaah-qaggq-cai.raw.ic0.app/",
        logo: "https://i.postimg.cc/rssdJ2TG/cycles-bet-cover.png",
        cover: "https://i.postimg.cc/rssdJ2TG/cycles-bet-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "",
        twitterHandle: "",
    },
    {
        id: "origyn-foundation",
        name: "ORIGYN Foundation",
        category: "NFTs",
        website: "https://www.origyn.ch/",
        canister: "",
        logo: "https://i.postimg.cc/4drY2wXG/origyn-foundation-logo.jpg",
        cover: "https://i.postimg.cc/RZMNYWxW/origyn-foundation-cover.jpg",
        twitter: "https://twitter.com/ORIGYNTech",
        github: "",
        telegram: "https://t.me/origynfoundation",
        slack: "",
        discord: "",
        medium: "",
        description: "We are on a mission to identify, authenticate and unlock the powers of ownership for objects of value.",
        twitterHandle: "ORIGYNTech",
    },
    {
        id: "nns-dapp",
        name: "NNS Dapp",
        category: "Wallets",
        website: "https://nns.ic0.app/",
        canister: "",
        logo: "https://i.postimg.cc/3rmrQskh/nnsdapp-logo.png",
        cover: "https://i.postimg.cc/Hswb0PHM/nns-dapp-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "The NNS front-end dapp allows anyone to interact with the Internet Computer's Network Nervous System with a user-friendly UI. Served completely end-to-end through blockchain, this dapp allows you to manage ICP, stake neurons, participate in voting, and earn rewards.",
        twitterHandle: "",
    },
    {
        id: "stoic-wallet",
        name: "Stoic Wallet",
        category: "Wallets",
        website: "https://www.stoicwallet.com/",
        canister: "",
        logo: "https://i.postimg.cc/JhzkpXRC/stoic-wallet-logo.png",
        cover: "https://i.postimg.cc/VLZ0Fypd/stoic-wallet-cover.png",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "",
        twitterHandle: "",
    },
    {
        id: "texas-poker",
        name: "Texas Poker",
        category: "Games",
        website: "",
        canister: "https://lm5fh-ayaaa-aaaah-aafua-cai.ic0.app/",
        logo: "https://i.postimg.cc/0QxD74rZ/texas-poker-logo.png",
        cover: "https://i.postimg.cc/59zWXkLD/texas-poker-cover.jpg",
        twitter: "",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "",
        twitterHandle: "",
    },
    {
        id: "icme",
        name: "ICME",
        category: "dApps",
        website: "",
        canister: "sygsn-caaaa-aaaaf-qaahq-cai.raw.ic0.app",
        logo: "https://i.postimg.cc/dt4c9CpD/icme.jpg",
        cover: "https://i.postimg.cc/W1zLY3c8/icme-cover.png",
        twitter: "https://twitter.com/icme_app",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "The Internet Computer's first no-code, website builder.",
        twitterHandle: "icme_app",
    },
    {
        id: "aikin",
        name: "AIKIN",
        category: "dApps",
        website: "https://www.aikin.io/",
        canister: "",
        logo: "https://i.postimg.cc/j5XMyMXh/aikin-logo.jpg",
        cover: "https://i.postimg.cc/HnkBzbv1/aikin-cover.jpg",
        twitter: "https://twitter.com/AikinDApps",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "We are blockchain software development company building on the Internet Computer by Dfinity",
        twitterHandle: "AikinDApps",
    },
    {
        id: "interconnect-network",
        name: "interconnect.network",
        category: "Social Networks",
        website: "https://interconnect.network/",
        canister: "",
        logo: "https://i.postimg.cc/FFMSTFKS/interconnect-network-logo.jpg",
        cover: "https://i.postimg.cc/k5Y6KqZB/interconnect-network-cover.jpg",
        twitter: "https://twitter.com/interconnect_nw",
        github: "",
        telegram: "",
        slack: "",
        discord: "",
        medium: "",
        description: "become mutually connected ∞ built on Dfinity The Internet Computer",
        twitterHandle: "interconnect_nw",
    },
]
